// Pre-curated viral promo ideas. Designed to look AI-generated.
// Sorted by platform and tagged with genres they fit best.
// When we have API budget later, swap this for a real Claude call — UI stays the same.

export const PLATFORMS = [
  { id: 'tiktok', label: 'TikTok' },
  { id: 'reels', label: 'Instagram Reels' },
  { id: 'shorts', label: 'YouTube Shorts' },
  { id: 'twitter', label: 'X / Twitter' },
];

export const IDEAS = [
  // ============== TIKTOK ==============
  {
    platform: 'tiktok',
    genres: ['HIP-HOP', 'DRILL', 'TRAP'],
    hook: 'The "Hand Camera Pass-Off"',
    concept: 'Start the video holding the camera. Mid-line, pass it to someone off-screen who catches it without breaking the beat. The transition becomes the meme.',
    shotList: '1 take, two people, indoor. Practice the hand-off 10x before recording. Camera must keep filming the entire pass.',
    why: 'Seamless physical transitions trigger replays. Algorithm rewards re-watches above 80%.',
    caption: 'who caught it 👀 [TRACK NAME] out now',
    hashtags: '#fyp #rap #newmusic',
    difficulty: 'Easy',
  },
  {
    platform: 'tiktok',
    genres: ['HIP-HOP', 'DRILL', 'TRAP', 'R&B'],
    hook: 'The "Wrong Lyric" Switch',
    concept: 'Lipsync the wrong lyrics for 4 seconds with total confidence. Then a smash cut to the real lyrics, real attitude, real song. The fakeout is the hook.',
    shotList: 'Same outfit, same location, two takes spliced. First take: deadpan, wrong words. Second take: in-the-zone, real song.',
    why: 'Pattern interrupts dwell time → algorithm boost. Comments fill up with "I thought it was real."',
    caption: 'admit it I had you for a second',
    hashtags: '#fyp #fakeout #newrapper',
    difficulty: 'Easy',
  },
  {
    platform: 'tiktok',
    genres: ['HIP-HOP', 'DRILL', 'TRAP'],
    hook: '"POV: you walked into the wrong block"',
    concept: 'Static phone on a tripod. You walk into frame mid-bar like the camera caught you slipping. Dead stare into lens for the drop. Walk back out.',
    shotList: '15 seconds. One take. Outdoor at golden hour for the orange tint. Audio sync is everything — practice your bar count.',
    why: 'POV format keeps thumb hovering. Stillness in the middle of audio chaos = scroll-stopper.',
    caption: 'mind ya business 🚶🏽',
    hashtags: '#fyp #pov #unsignedhype',
    difficulty: 'Easy',
  },
  {
    platform: 'tiktok',
    genres: ['HIP-HOP', 'R&B', 'POP', 'INDIE'],
    hook: '"Songs that healed me in 2026"',
    concept: 'Slideshow of 5–7 album covers with your own as the LAST one. Slow zoom in. The reveal at the end is the play.',
    shotList: 'No filming — built in CapCut. Use other artists\' covers (fair use for commentary). Yours appears last, biggest, with track name.',
    why: 'Hijacks "songs that..." search trend. People stitch their own version → free distribution.',
    caption: 'they don\'t play these on radio',
    hashtags: '#fyp #musicrecs #hiddenmusic',
    difficulty: 'Easy',
  },
  {
    platform: 'tiktok',
    genres: ['HIP-HOP', 'DRILL', 'TRAP'],
    hook: 'The "30 Second Story"',
    concept: 'Use your hook as the soundtrack. Type captions on screen that tell a quick story (you got cheated on / broke / heated argument) that LINES UP with the lyrics word for word.',
    shotList: 'Static shot of you. Text overlay does the work. Each text block hits exactly on a lyric.',
    why: 'Storytime format = highest avg watch time of any TikTok genre. Lyric sync makes the song unforgettable.',
    caption: 'this song is about a real night',
    hashtags: '#fyp #storytime #rap',
    difficulty: 'Medium',
  },
  {
    platform: 'tiktok',
    genres: ['R&B', 'SOUL', 'POP', 'INDIE'],
    hook: 'The "Slow Zoom Into Eye Contact"',
    concept: 'Camera starts wide on you not paying attention. Slowly zooms to ECU on your eyes by the time the hook hits. Hold the stare for the chorus.',
    shotList: 'Phone on a sliding rig or just walk it in slowly. Sad lighting (curtains drawn, single lamp). Practice the eye intensity.',
    why: 'Intimacy + slow zoom = TikTok\'s most-saved format for R&B. Saves > likes in the algorithm.',
    caption: 'this one\'s for the ones who knew',
    hashtags: '#fyp #rnb #softpop',
    difficulty: 'Easy',
  },
  {
    platform: 'tiktok',
    genres: ['HIP-HOP', 'DRILL', 'TRAP', 'R&B'],
    hook: '"I bet I can rap this fast"',
    concept: 'Set up the camera. Look at it. Say "bet you can\'t catch every word." Then drop your hardest 8 bars at speed. Type the lyrics on screen in real time so people can verify.',
    shotList: 'One take, dead serious face. Captions burned in via CapCut auto-captions (then corrected manually for spelling/punchlines).',
    why: 'Challenge framing = comment bait ("ok but slowed down... still hits"). Captions also help foreign audiences share.',
    caption: 'count the bars in comments',
    hashtags: '#fyp #fastrap #lyrics',
    difficulty: 'Medium',
  },
  {
    platform: 'tiktok',
    genres: ['HIP-HOP', 'POP', 'INDIE', 'ELECTRONIC'],
    hook: 'The "Outfit Drop Reveal"',
    concept: 'You\'re wearing all black. Camera spins around you while the beat builds. On the drop, smash cut to you in a completely different fit. Lighting changes too.',
    shotList: 'Two takes, same spot. Costume change in between. Phone gimbal helps but iPhone stabilization works.',
    why: 'Fits = TikTok currency. Costume changes get reposted to fit accounts → cross-niche reach.',
    caption: 'POV: the beat changed me',
    hashtags: '#fyp #fitcheck #newmusic',
    difficulty: 'Medium',
  },

  // ============== INSTAGRAM REELS ==============
  {
    platform: 'reels',
    genres: ['HIP-HOP', 'DRILL', 'TRAP', 'R&B', 'POP'],
    hook: 'The "Voice Memo" Tease',
    concept: 'Black screen. Phone interface showing a voice memo titled "[track name] DEMO". Hit play. The actual track plays for 15 seconds with a wave animation.',
    shotList: 'Screen-recorded on iPhone voice memos. Replace the audio with your unreleased clip. Add subtle hand-holding-phone shake.',
    why: 'Looks like a leak. Triggers FOMO. People DM each other "did you see [name]\'s demo??"',
    caption: 'unreleased. dropping [DATE]',
    hashtags: '#newmusic #unreleased #demo',
    difficulty: 'Easy',
  },
  {
    platform: 'reels',
    genres: ['HIP-HOP', 'DRILL', 'TRAP'],
    hook: '"The Studio Reaction"',
    concept: 'Film your engineer/producer/friend hearing the track for the first time. Their honest reaction is the whole video. Bonus if they say "oh nah" or grab their head.',
    shotList: 'Have someone film while you play the unreleased track. Don\'t fake reactions — even mild ones land. Cut to 20 seconds max.',
    why: 'Reaction content has the highest average completion rate on Reels. Reposted by music pages.',
    caption: 'his face after the second verse',
    hashtags: '#newmusic #studio #reaction',
    difficulty: 'Easy',
  },
  {
    platform: 'reels',
    genres: ['HIP-HOP', 'R&B', 'POP', 'INDIE'],
    hook: '"Songs that hit different at 3am"',
    concept: 'Slow handheld walk through your room/apartment at night. Lo-fi grain. Lights low. Your song plays as the soundtrack. Caption: "songs that hit different at 3am 🌙"',
    shotList: 'Phone in hand, walk slowly. Night lighting (one warm lamp). 25 seconds.',
    why: 'Aesthetic carousels get saved 3x more than they get liked. Saves = algorithm gold.',
    caption: 'this one feels like a memory',
    hashtags: '#aesthetic #latenight #mood',
    difficulty: 'Easy',
  },
  {
    platform: 'reels',
    genres: ['HIP-HOP', 'DRILL', 'TRAP'],
    hook: '"Dropping [DATE] — comment your city"',
    concept: 'Static cover art with the release date over it. Your hook as audio. Caption says "tell me your city, I\'ll tell you if I\'m coming." Reply to every comment with a city name.',
    shotList: 'No filming. Just Canva or CapCut. The work happens in the comments.',
    why: 'Comments are the single most weighted engagement signal. 100 city replies = algorithm explosion.',
    caption: 'where you at 👇',
    hashtags: '#newmusic #tour #dropping',
    difficulty: 'Easy',
  },
  {
    platform: 'reels',
    genres: ['R&B', 'SOUL', 'INDIE', 'POP'],
    hook: '"The Lyric That Hurts"',
    concept: 'Type your saddest/realest lyric in white text on a black screen. Hold for 4 seconds in silence. Then the song plays underneath it for the rest of the reel.',
    shotList: 'Pure text + audio. CapCut. No filming. The lyric should be relatable but specific (heartbreak, growth, regret).',
    why: 'Lyric pages on IG (with millions of followers) repost these for free if the line hits.',
    caption: 'wrote this at 2am',
    hashtags: '#lyrics #sadlyrics #newmusic',
    difficulty: 'Easy',
  },

  // ============== YOUTUBE SHORTS ==============
  {
    platform: 'shorts',
    genres: ['HIP-HOP', 'DRILL', 'TRAP', 'R&B'],
    hook: '"Making [TRACK] in 60 Seconds"',
    concept: 'Speedrun your beat → melody → hook → final mix. Each stage 10 seconds. End with the finished track playing over the cover art.',
    shotList: 'Screen-record your DAW. Voice-over each stage briefly. Last 20 seconds = pure track.',
    why: 'YouTube Shorts pushes "how I made" music content hard — producer audience is huge there.',
    caption: 'How I made [TRACK] — out now',
    hashtags: '#musicproduction #beatmaking #shorts',
    difficulty: 'Medium',
  },
  {
    platform: 'shorts',
    genres: ['HIP-HOP', 'DRILL', 'TRAP'],
    hook: '"First Listen Reaction Compilation"',
    concept: 'Compile 5 different friends\' first reactions to your unreleased track. Each clip 8 seconds. End with cover art + release date.',
    shotList: 'Film at different times/locations. The variety sells it. Capture genuine moments, not staged.',
    why: 'Compilation format = high retention. YouTube\'s algorithm loves multi-cut Shorts.',
    caption: 'I asked 5 friends to react to my new song',
    hashtags: '#reaction #newmusic #unreleased',
    difficulty: 'Medium',
  },
  {
    platform: 'shorts',
    genres: ['HIP-HOP', 'R&B', 'POP', 'INDIE', 'ELECTRONIC'],
    hook: '"This song matches this vibe"',
    concept: 'Cinematic 30-second shot of one specific vibe (driving at night, walking in rain, empty subway). Your song plays. No talking, just visuals + audio.',
    shotList: 'Phone with stabilization. Color-grade in CapCut (lower exposure, raise contrast, add slight blue tint).',
    why: 'Vibe Shorts get saved + sent to friends. Strong "save" signal beats most likes.',
    caption: 'made this for nights like this',
    hashtags: '#cinematic #moody #musicvideo',
    difficulty: 'Medium',
  },
  {
    platform: 'shorts',
    genres: ['HIP-HOP', 'DRILL', 'TRAP'],
    hook: '"Type Beat Challenge"',
    concept: 'Title: "I rapped on a [BIG ARTIST] type beat in 60 seconds." Show the beat\'s YouTube tab, screen-record yourself recording, end with the snippet.',
    shotList: 'Screen + face cam combo. Use a real free type beat from YouTube (credit producer in description).',
    why: 'Searches for "[big artist] type beat" rank high. Your Short surfaces in those searches.',
    caption: 'tagging [big artist] but he\'ll never see this 😭',
    hashtags: '#typebeat #freestyle #rap',
    difficulty: 'Medium',
  },

  // ============== X / TWITTER ==============
  {
    platform: 'twitter',
    genres: ['HIP-HOP', 'DRILL', 'TRAP', 'R&B', 'POP', 'INDIE'],
    hook: '"I made a song about [X]. RT if you can relate."',
    concept: 'One-tweet hook. State the song\'s specific emotional theme. Attach a 30-second clip. End with "drops [DATE]." No links — links kill reach on X.',
    shotList: 'Vertical clip, hook only. The tweet copy does the heavy lifting.',
    why: 'Relatable specificity > generic hype. "Song about being ghosted by your best friend" beats "new music out."',
    caption: 'song about pretending you\'re fine in front of family',
    hashtags: 'no hashtags on X — they kill algorithm reach',
    difficulty: 'Easy',
  },
  {
    platform: 'twitter',
    genres: ['HIP-HOP', 'DRILL', 'TRAP'],
    hook: 'The "Bar Drop"',
    concept: 'Just text. The hardest bar from your unreleased track. No context. No "out now" attached. Let it sit on the timeline alone.',
    shotList: 'No video. Just text. Black background, white text if you want the screenshot look.',
    why: 'Quotable bars get screenshotted and reposted forever. Best case: it goes viral before the song drops.',
    caption: '[INSERT YOUR HARDEST BAR — no song title, no link]',
    hashtags: 'none',
    difficulty: 'Easy',
  },
  {
    platform: 'twitter',
    genres: ['HIP-HOP', 'DRILL', 'TRAP', 'R&B', 'POP', 'INDIE'],
    hook: 'The "Founder Tweet"',
    concept: 'A "behind the scenes" thread about how you made the song. 4 tweets max. Start with "spent 3 months on this song. here\'s what I learned." Replies count more than likes.',
    shotList: 'No filming. Pure text storytelling. Include 1 photo of the studio or your phone\'s notes app.',
    why: 'X rewards REPLIES above all. Founder/builder content gets reply-heavy responses.',
    caption: 'spent 3 months on this song. here\'s what changed:',
    hashtags: 'none',
    difficulty: 'Easy',
  },
  {
    platform: 'twitter',
    genres: ['HIP-HOP', 'DRILL', 'TRAP', 'R&B'],
    hook: '"Snippet vs Final"',
    concept: 'Quote-tweet an old snippet you posted months ago. Caption: "here\'s the finished version." Attach the final clip.',
    shotList: 'Find your own old tweet. Quote-tweet it with the polished version. Closes the loop visually.',
    why: 'QTs of your own old posts re-surface to people who saw the snippet → high context, high CTR.',
    caption: 'finally finished',
    hashtags: 'none',
    difficulty: 'Easy',
  },
  {
    platform: 'twitter',
    genres: ['HIP-HOP', 'R&B', 'POP', 'INDIE'],
    hook: '"Three songs to add to your playlist"',
    concept: 'List 2 other artists + you as #3. Specific niche playlists. "3 songs for crying in your car at 1am" — your track + 2 you genuinely love.',
    shotList: 'No filming. Pure text + 3 cover art images attached.',
    why: 'Listicle format gets bookmarked. The other 2 artists may notice and RT.',
    caption: '3 songs to play when you can\'t sleep',
    hashtags: 'none',
    difficulty: 'Easy',
  },

  // ============== MORE GENRES — Electronic / Indie / Ambient ==============
  {
    platform: 'tiktok',
    genres: ['ELECTRONIC', 'HOUSE', 'TECHNO'],
    hook: 'The "Build to Drop"',
    concept: 'Static frame. Visualizer overlay on your face/silhouette. Frequency bars build with the song. At the drop, smash cut to a strobe + chaos.',
    shotList: 'Phone tripod. Visualizer added in CapCut (free presets). Strobe effect: rapid flash transitions.',
    why: 'Audio-reactive visuals own electronic music TikTok. Algorithm tags it as "electronic content" and serves it to that niche.',
    caption: 'when the bass dropped 💀',
    hashtags: '#fyp #edm #drop',
    difficulty: 'Medium',
  },
  {
    platform: 'reels',
    genres: ['INDIE', 'AMBIENT', 'LO-FI'],
    hook: 'The "Field Recording" Aesthetic',
    concept: 'Slow handheld B-roll of a coffee shop / train window / forest path. Your ambient/indie track plays. Caption: "this song belongs to [the place]."',
    shotList: 'Phone, walk slowly, no narration. CapCut: lower saturation, raise contrast, add Super 8 film grain preset.',
    why: 'Aesthetic indie content gets saved + shared to "mood" playlists. Premium audience = paying listeners.',
    caption: 'this one belongs to rainy commutes',
    hashtags: '#aesthetic #indie #mood',
    difficulty: 'Easy',
  },
  {
    platform: 'tiktok',
    genres: ['AFROBEATS', 'DANCEHALL', 'LATIN'],
    hook: 'The "Two-Step Reveal"',
    concept: 'Start the video casually walking. Hook drops. You hit a SPECIFIC 4-count dance move on the beat. Repeat it twice and exit frame.',
    shotList: 'Outdoor in motion. The move needs to be replicable in 5 seconds — that\'s how it becomes a trend.',
    why: 'Simple dances spread. If the move is easy to copy, the audio attaches to it and travels.',
    caption: 'try it — tag me 👀',
    hashtags: '#fyp #dancechallenge #afrobeats',
    difficulty: 'Medium',
  },
  {
    platform: 'shorts',
    genres: ['HIP-HOP', 'DRILL', 'TRAP', 'POP', 'R&B'],
    hook: '"Day in the life dropping a song"',
    concept: 'Vlog the literal day your song drops. Morning routine → studio check → friends listening → end with stream counts at midnight.',
    shotList: 'Phone for the whole day. Edit down to 60 seconds. Music is your own track underneath.',
    why: 'Day-in-the-life format = highest YouTube Shorts retention category. Builds parasocial bond → repeat listeners.',
    caption: 'release day. here\'s how it actually went',
    hashtags: '#dayinmylife #releaseday #independentartist',
    difficulty: 'Medium',
  },
];

/**
 * Pick a random idea matching platform + (optional) genres.
 * Returns the full idea object. Falls back to any platform match if no genre match.
 */
export function pickRandomIdea({ platform, genres = [], exclude = [] }) {
  const matchesGenre = (idea) => {
    if (!genres.length) return true;
    return idea.genres.some((g) => genres.map((x) => x.toUpperCase()).includes(g));
  };
  const pool = IDEAS.filter((i) => i.platform === platform && !exclude.includes(i.hook));
  const genreMatched = pool.filter(matchesGenre);
  const final = genreMatched.length > 0 ? genreMatched : pool;
  if (final.length === 0) return null;
  return final[Math.floor(Math.random() * final.length)];
}
